import { FunctionComponent } from 'react';
import {
  HiBell,
  HiChevronDown,
  HiChevronLeft,
  HiChevronRight,
  HiChevronUp,
  HiCog,
  HiDotsVertical,
  HiDownload,
  HiMail,
  HiOutlineBriefcase,
  HiOutlineCalculator,
  HiOutlineCalendar,
  HiOutlineCheck,
  HiOutlineCollection,
  HiOutlineDocumentDuplicate,
  HiOutlineEye,
  HiOutlineHome,
  HiOutlineLogout,
  HiOutlineOfficeBuilding,
  HiOutlinePencil,
  HiOutlinePlus,
  HiOutlineRefresh,
  HiOutlineTrash,
  HiOutlineUser,
  HiOutlineUsers,
  HiX,
} from 'react-icons/hi';
import { Icon } from '../enums';
import { IconProps } from '../types';

export const ICON_CONFIG: Record<Icon, FunctionComponent<IconProps>> = {
  [Icon.bell]: HiBell,
  [Icon.briefcase]: HiOutlineBriefcase,
  [Icon.calculator]: HiOutlineCalculator,
  [Icon.calendar]: HiOutlineCalendar,
  [Icon.check]: HiOutlineCheck,
  [Icon.close]: HiX,
  [Icon.cog]: HiCog,
  [Icon.collection]: HiOutlineCollection,
  [Icon.delete]: HiOutlineTrash,
  [Icon.documents]: HiOutlineDocumentDuplicate,
  [Icon.dots]: HiDotsVertical,
  [Icon.down]: HiChevronDown,
  [Icon.download]: HiDownload,
  [Icon.edit]: HiOutlinePencil,
  [Icon.home]: HiOutlineHome,
  [Icon.left]: HiChevronLeft,
  [Icon.loading]: HiOutlineRefresh,
  [Icon.logout]: HiOutlineLogout,
  [Icon.mail]: HiMail,
  [Icon.office]: HiOutlineOfficeBuilding,
  [Icon.plus]: HiOutlinePlus,
  [Icon.right]: HiChevronRight,
  [Icon.up]: HiChevronUp,
  [Icon.users]: HiOutlineUsers,
  [Icon.user]: HiOutlineUser,
  [Icon.view]: HiOutlineEye,
};
